### ISSUE TITLE
Epic: ML model development

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#88]
Once we have a real AI set up and a real training dataset available, it is time to train the AI with the dataset.

### Tasks

- [x] [Fundamental research](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/23) (also #20 and #34)
- [x] [Create prototype](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/22) 
- [x] [Preprocess collected data](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/19)
- [x] [Create first iteration of working predictor](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/154)
- [x] Evaluate prediction results / identify issues
- [x] Create improved iteration
- [x] Further evaluation
- [x] Fine tuning
